### ISSUE TITLE
No Tkinter for Comfy

### ISSUE THREAD

**Issue by Amorano** [jags111/ComfyUI_Jags_Audiotools#5]
ComfyUI's embedded doesnt come with TKinter.

![image](https://github.com/jags111/ComfyUI_Jags_Audiotools/assets/225178/d786c079-0175-4077-a1b0-12f380cb7b10)

That should also be an external requirement which is gonna be sad times since you cant pip install tkinter and Comfyui embedded .....

**Comment by Amorano** [comment]
After taking a look, you dont even use TKinter. =D  You can just remove the import.

![image](https://github.com/jags111/ComfyUI_Jags_Audiotools/assets/225178/32f99b60-a7d9-4e67-bd11-6bd3de6b8b5a)


fixes the issue; along with removing all the other dead imports.

**Comment by jags111** [comment]
sure will do same.. as i was trying the library for the audio play

**Comment by jags111** [comment]
thanks for your pull and completed same
