### ISSUE TITLE
__pycache__

### ISSUE THREAD

**Issue by Amorano** [jags111/ComfyUI_Jags_Audiotools#7]
The __pycache__ folders should not be in the repo.

**Comment by jags111** [comment]
sure .. my error in copy and adding

**Comment by jags111** [comment]
Hai.. if you feel something can be done to improve the repo and add any issues ... please feel free to message and send a comment for same. Very much appreciate your time to solve the issues which did not get updated and will be taking time out to add more nodes and clear the sound player issues.
